CREATE DATABASE parking_app_database;
USE parking_app_database;

CREATE TABLE My_Users (
sr_id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
group_id VARCHAR(30),
user_id VARCHAR(30) NOT NULL,
firstname VARCHAR(30) NOT NULL,
lastname VARCHAR(30) NOT NULL,
phone_no VARCHAR(20) NOT NULL,
email VARCHAR(50) NOT NULL,
user_type VARCHAR(30) NOT NULL,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE My_Parkings (
sr_id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
group_id VARCHAR(30) NOT NULL,
parking_id VARCHAR(30) NOT NULL,
parking_status VARCHAR(30) NOT NULL,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE My_Jobs (
sr_id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
group_id VARCHAR(30),
job_id VARCHAR(30),
user_id VARCHAR(30),
parking_id VARCHAR(30),
job_status VARCHAR(30),
in_time VARCHAR(30),
out_time VARCHAR(30),
customer_name VARCHAR(30),
customer_phone VARCHAR(20),
customer_car_no VARCHAR(20),
customer_license VARCHAR(30),
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
